### ISSUE TITLE
Why not export function debounce from useDebouce? useThrottle does the same, exports throttle.

### ISSUE THREAD

**Issue by gremo** [stimulus-use/stimulus-use#208]
In [`useThrottle`](https://github.com/stimulus-use/stimulus-use/blob/main/src/use-throttle/use-throttle.ts#L14) the `throttle` function, this is actually good to use in custom hooks or utilities, without copy & paste the code. The same doesn't happen for [`useDebouce`](https://github.com/stimulus-use/stimulus-use/blob/main/src/use-debounce/use-debounce.ts#L14). Why?

IMHO either be consistent, hiding `throttle` too... or export also `debouce`. Since removing `export function throttle` is a BC break, I would simply `export function debounce` .

**Comment by marcoroth** [comment]
The `throttle` function is just exported out of that file, but not globally out of the package. See:

https://github.com/stimulus-use/stimulus-use/blob/3cd45d216643c1552705f9b9d560955f596e5b67/src/index.ts#L13-L14

So you can't really import either of the two functions in your app.

Though, it might make sense to export both of them also from the package, so that you can make use of them in your app. But on the other hand this package is meant for the `use`-behaviors, so I'm not sure if this is the right move. 

Keeping them private also means that we can change the implementation without breaking the composable behaviors.

**Comment by gremo** [comment]
Agree, you are perfectly right about the "use" behaviour. My bad, I'll close this.
