### ISSUE TITLE
`useIntersection` for multiple elements not calls `disappear`

### ISSUE THREAD

**Issue by ocarreterom** [stimulus-use/stimulus-use#211]
Controller example:
```js
import { Controller } from '@hotwired/stimulus';
import { useIntersection } from 'stimulus-use';

class ListController extends Controller {
  static targets = ['item'];

  connect() {
    for (const item of this.itemTargets) {
      useIntersection(this, { element: item, root: this.element });
    }
  }

  appear() {
    console.log('✅ appear');
  }

  disappear() {
    console.log('❌ disappear');
  }
}
```

Example: https://stackblitz.com/edit/js-1pzvcb?file=index.js

https://user-images.githubusercontent.com/11599942/180796105-216a5088-a11d-4aa4-8eb9-d81abea4f493.mov

**Comment by marcoroth** [comment]
Hey @ocarreterom, thanks for reporting this!

This seems indeed like a bug. I think the problem is that we are setting `controller.isVisible = false` here as soon as the first `disappear` is called:
https://github.com/stimulus-use/stimulus-use/blob/aafc27fc126d52801ba412a7a1ef80bfd4203bd3/src/use-intersection/use-intersection.ts#L42

Because of that the next `disappear` event is not being dispatched because we check for `else if (controller.isVisible)` before we dispatch the `disappear ` callback here:
https://github.com/stimulus-use/stimulus-use/blob/aafc27fc126d52801ba412a7a1ef80bfd4203bd3/src/use-intersection/use-intersection.ts#L23

Maybe @adrienpoly has an idea if and how we might be able to support multiple elements while keeping the `isVisible` logic in there.

If I understand right, I think the logic is needed so that we don't call the callbacks more than once if the intersection event is triggered more than once. If that's the case, we might be able to change were we store this `isVisible` information. We could move it from the controller to the element, so every element keep track of their own state.
