### ISSUE TITLE
`useIdle`: Typescript error: argument of type 'this' is not assignable to parameter of type "IdleComposableController"

### ISSUE THREAD

**Issue by gremo** [stimulus-use/stimulus-use#213]
Because of [this declaration](https://github.com/stimulus-use/stimulus-use/blob/main/src/use-idle/idle-controller.ts#L5) in `IdleComposableController `, there is the following Typescript error:

> Argument of type 'this' is not assignable to parameter of type 'IdleComposableController'.
  Property 'isIdle' is missing in type 'default' but required in type 'IdleComposableController'.

```typescript
import { Controller } from '@hotwired/stimulus';
import { useIdle } from 'stimulus-use';

export default class extends Controller<HTMLElement> {
  connect() {
    useIdle(this);
  }
}
```

I don't know why that property exists in the first place. It's being setted on:
- https://github.com/stimulus-use/stimulus-use/blob/main/src/use-idle/use-idle.ts#L35
- https://github.com/stimulus-use/stimulus-use/blob/main/src/use-idle/use-idle.ts#L47

Could be solved by `declare isIdle: boolean`... is this my bad or the intended way?

**Comment by marcoroth** [comment]
Hey @gremo, thanks for reporting this!

Are you using this with Stimulus 3.1, right? I think it might have to do with new the support for extending Stimulus controllers within Stimulus itself (https://github.com/hotwired/stimulus/pull/529). 

And because of that the controller types don't line up anymore because you are extending your controller with a generic and not just a controller.

I think we need to slightly modify this is `stimulus-use` to comply with this new change.
