### ISSUE TITLE
Possible to exclude hotkeys from generated JS?

### ISSUE THREAD

**Issue by marckohlbrugge** [stimulus-use/stimulus-use#237]
I'm not using they hotkeys mixin, but `hotkeys-js` still ends up being included in my application.js

I think it's because when I use a mixin like`useIntersection` it will include `stimulus-use/index.js` which immediately imports `hotkeys-js`.

I'm not familar with Typescript, so I can't point to the source code that causes this. But I see the compiled `node_modules/stimulus-use/dist/index.js` which shows this:

```javascript
/*
Stimulus-Use 0.50.0
*/
import { Controller } from '@hotwired/stimulus';
import hotkeys from 'hotkeys-js';
```

Would it make sense to make this import part of the hotkeys mixin somehow? So it only gets imported when the hotkeys mixin is used.

**Comment by marcoroth** [comment]
Hey @marckohlbrugge, the reason why it's included like that now is because of #156.

First it was declared as a peer dependency, but currently it is included in the application.js. Technically if you are using a bundler and it's properly configured it should tree-shake this uneededed code out.

One other solution could be (which would be a breaking change) that we move the dependency back to a peer Dependency, so that the user needs to explicitly add it to their package.json. 

With that we could then move the import to the hotkeys file itself as you suggest, remove the `export useHoteys ...` from the `index.ts` and define an export map for `stimulus-use/hotkeys`. 

Then end-users need to import the mixing from something like:
 ```js
import useHotkeys from "stimulus-use/hotkeys"
```

I wouldn't be opposed to a solution like this, since that would also allow more mixins for external plugins to be included with stimulus-use, without the need to install the dependency if you are not actually using the mixin.

**Comment by marckohlbrugge** [comment]
@marcoroth Thanks for the context!

I’ll look into why hotkeys isn’t been tree-shaked out. I have a fairly standard / simple Rails 7 JavaScript setup (no more webpacker etc) so that might explain it.

As for making it a peer dependency that does seem like the most flexible option to me. Like you say it would make it more inviting for contributors to add additional mix-ins that need dependencies.

If you can show a proper error message when the hotkeys mix-in is used without the required dependency installed, then I imagine it won’t be that much of a hassle for anyone who does want it.

**Comment by marcoroth** [comment]
I've put up #262 which should resolve this issue

**Comment by marcoroth** [comment]
@all-contributors add @marckohlbrugge for ideas
