### ISSUE TITLE
Error: Unable to resolve specifier 'stimulus-use/hotkeys'

### ISSUE THREAD

**Issue by bdtomlin** [stimulus-use/stimulus-use#296]
Just found this library today. Very cool. It really helps bring stimulus up to par with things like alpine.

Upon following the instructions for hotkeys I get this error: `Error: Unable to resolve specifier 'stimulus-use/hotkeys'`

I'm importing hotkeys as follows:

`import { useHotkeys } from "stimulus-use/hotkeys";`

I also have it in my import map like this:

`pin "hotkeys-js", to: "https://ga.jspm.io/npm:hotkeys-js@3.10.1/dist/hotkeys.esm.js"`

I'm no expert on import maps, but I can say the instructions in the docs don't produce a working result for me. Any ideas on what the problem could be?

**Comment by marcoroth** [comment]
Hey @bdtomlin, thanks for opening this issue!

I think the problem is that `stimulus-use` and `stimulus-use/hotkeys` are basically seen as "two packages" (or identifiers) for importmaps. Meaning that you also need to have two pins in your import map config. Currently you probably have this in your `config/importmap.rb`:

```ruby
pin "stimulus-use", to: "https://ga.jspm.io/npm:stimulus-use@0.52.0/dist/index.js"
```

And I think you would also need something like this too:
```ruby
pin "stimulus-use/hotkeys", to: "https://ga.jspm.io/npm:stimulus-use@0.52.0/dist/hotkeys.js"
```
You should be able to achieve the above if you run `bin/importmap pin stimulus-use/hotkeys`.

I hope this helps!

**Comment by bdtomlin** [comment]
Yep, that's exactly what I needed. Thanks for your quick response. I didn't realize `stimulus-use/hotkeys` was a completely separate project.

**Comment by marcoroth** [comment]
Oh, `stimulus-use/hotkeys` is still part of the `stimulus-use` package. 

But an npm package can export and bundle up multiple files/entrypoints in a single package. These are usually defined in the package.json and are called "export maps". See here:
https://github.com/stimulus-use/stimulus-use/blob/88228048349bbc408aa0994eafd0dd342ed1912b/package.json#L17-L33

But due to the nature how import maps work you need to pin each entrypoint from the export maps list you are using.

This wasn't obvious, I'm going to add a remark for this in the docs! Thanks for bringing this up! 🙌🏼

**Comment by bdtomlin** [comment]
Thanks Marco, I learned something about import maps and export maps! Thanks for your great attitude and helpfulness.
