### ISSUE TITLE
`yarn` hasn't installed even though it is used in npm-scripts `npm run clean`

### ISSUE THREAD

**Issue by lidqqq** [stimulus-use/stimulus-use#40]
Hi 🍕 

When I tried to run `npm run build`, an error occurred which said `yarn: command not found`.

I think some people haven't installed yarn as a global modules.

Should we install yarn in devDependencies ? what do you think? 👀

**Comment by adrienpoly** [comment]
Hey 

yes I mostly use `yarn` so that is a valid point for npm users 

as per this answer on SO https://stackoverflow.com/questions/41647961/package-json-scripts-that-work-with-npm-and-yarn
I think the best would be to replace prebuilt like this

```
"prebuild": "$npm_execpath run clean",
```

did a quick test and it seems to work 

if you can confirm on your side and/or open a PR thanks

**Comment by lidqqq** [comment]
@adrienpoly 
Thanks for quick reply !! 🏎️ 

That's a wonderful way! I've not known this approach.
